version: "3.9"

services:
  Chat_ibict:
    image: chat_ibict
    container_name: char_ibict
    build:
      context: .
      dockerfile: ./Dockerfiles/Dockerfile.chat
    entrypoint: "tail -f /dev/null"
    volumes:
      - ".:/code"
    depends_on:
      - db
    restart: always
    networks:
      - postgres-connection

  db:
    container_name: chat_postgres_container
    build: 
      context: .
      dockerfile: ./Dockerfiles/Dockerfile.postgrees
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: SENHA
      PGDATA: /data/postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    expose:
      - "5432"
    restart: always
    networks:
      - postgres-connection

  

networks:
  postgres-connection:
    driver: bridge
