version: "3.9"

services:
  Chat_ibict:
    image: chat_ibict
    container_name: char_ibict
    build:
      context: .
      dockerfile: Dockerfiles/dockerfile.chat
    entrypoint: "tail -f /dev/null"
    volumes:
      - ".:/app"
    depends_on:
      - db
    restart: always
    networks:
      - postgres-connection

  db:
    container_name: postgres_container
    build: 
      context: .
      dockerfile: Dockerfiles/dockerfile.postgrees
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
    ports:
      - "5432:5432"
    expose:
      - "5432"
    restart: always
    networks:
      - postgres-connection

  

networks:
  postgres-connection:
    driver: bridge
