# Generated by Django 4.2 on 2023-05-12 15:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=30)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
        ),
        migrations.CreateModel(
            name='Dicionario',
            fields=[
                ('IDunico', models.IntegerField(primary_key=True, serialize=False)),
                ('IDSignificado', models.IntegerField()),
                ('Palavra', models.CharField(max_length=1500)),
            ],
        ),
        migrations.CreateModel(
            name='ResultML',
            fields=[
                ('idML', models.IntegerField(primary_key=True, serialize=False)),
                ('noun', models.CharField(max_length=1500)),
                ('prevRFrang', models.CharField(max_length=1500)),
                ('prevC50', models.CharField(max_length=1500)),
                ('prevRpart', models.CharField(max_length=1500)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('testId', models.AutoField(primary_key=True, serialize=False)),
                ('phraseTest', models.CharField(max_length=1500)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='email')),
            ],
        ),
        migrations.CreateModel(
            name='Noun',
            fields=[
                ('nounId', models.AutoField(primary_key=True, serialize=False)),
                ('nounText', models.CharField(max_length=1500)),
                ('idSignificado', models.CharField(max_length=1500)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paginas.test')),
            ],
        ),
    ]
