# Generated by Django 4.2.2 on 2023-07-04 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0002_remove_customuser_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='phraseTest',
            field=models.CharField(),
        ),
    ]
