# Generated by Django 4.2.2 on 2023-12-14 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0003_customuser_is_active_alter_test_phrasetest'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='title',
            field=models.CharField(default='Default Title', max_length=200),
        ),
    ]
